### ISSUE TITLE
Compiling failure

### ISSUE THREAD

**Issue by anvme** [tonlabs/TVM-linker#185]
Compiling failure v0.1.8
   Compiling ton_abi v0.1.0 (https://github.com/tonlabs/ton-labs-abi.git#5b4cdc64)
   Compiling ton_sdk v0.1.0 (https://github.com/tonlabs/ton-sdk.git#fd9462bf)
error[E0599]: no associated item named `MAX` found for type `u64` in the current scope
   --> /root/.cargo/git/checkouts/ton-sdk-11823a0ea1fdf592/fd9462b/ton_sdk/src/transaction.rs:237:53
    |
237 |         fees.total_output = if total_output <= u64::MAX as u128 { total_output as u64 } else { 0 };
    |                                                     ^^^ associated item not found in `u64`
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
            `use rand::distributions::weighted::alias_method::Weight;`
help: you are looking for the module in `std`, not the primitive type
    |
237 |         fees.total_output = if total_output <= std::u64::MAX as u128 { total_output as u64 } else { 0 };
    |                                                ^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `ton_sdk`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by buktop24** [comment]
Hi. Please make sure that you have a latest Rust 1.43.0.

**Comment by joydark** [comment]
Fixed in 562b2f29d7170432e3456ac3110cc59994f02190
