### ISSUE TITLE
Cannot link - Error: internal function with id = 0 already exist

### ISSUE THREAD

**Issue by BitLox** [tonlabs/TVM-linker#207]
Ubuntu 18.04.4 LTS

solc, the solidity compiler commandline interface
Version: 0.6.3-develop.2020.11.10+commit.35637a12.mod.Linux.g++

TVM linker 0.1.0
COMMIT_ID: 9856546f7eb15922c1fb3b07976c70c344931acf
BUILD_DATE: 2020-11-10 01:32:38 -0700
COMMIT_DATE: 2020-10-29 18:41:12 +0300
GIT_BRANCH: master
tvm_linker 0.1 ()

Compile 11_SimpleContract.sol 

```
ubuntu@bitlox:~/ton/samples/solidity/compiled$ solc ../11_SimpleContract.sol 
Code was generated and saved to file 11_SimpleContract.code
ABI was generated and saved to file 11_SimpleContract.abi.json
```
Compiled:
```
ubuntu@bitlox:~/ton/samples/solidity/compiled$ ls
11_SimpleContract.abi.json  11_SimpleContract.code
```
Attempt to generate TVM files:
```
ubuntu@bitlox:~/ton/samples/solidity/compiled$ tvm_linker compile 11_SimpleContract.code --lib /usr/local/lib/stdlib_sol.tvm --abi-json 11_SimpleContract.abi.json
TVM linker 0.1.0
COMMIT_ID: 9856546f7eb15922c1fb3b07976c70c344931acf
BUILD_DATE: 2020-11-10 01:32:38 -0700
COMMIT_DATE: 2020-10-29 18:41:12 +0300
GIT_BRANCH: master
Error: line 257: internal function with id = 0 already exist
Error: 1
```

Same issue on macOS 10.15 Catalina, also same error regardless of the contract used.

**Comment by joydark** [comment]
Thanks for reporting.
We will update stdlib_sol.tvm in this repository.
Meanwhile, you can update your version of stdlib_sol.tvm from https://github.com/tonlabs/TON-Solidity-Compiler/blob/master/lib/stdlib_sol.tvm

**Comment by SilkovAlexander** [comment]
Thank you for an issue, it seems, that you have used **stdlib_sol.tvm** from this repo and this file is needed only for tests. To compile TVM Solidity contracts, you should use lib from TON Solidity Compiler repo:
https://github.com/tonlabs/TON-Solidity-Compiler/blob/master/lib/stdlib_sol.tvm

**Comment by BitLox** [comment]
Thanks, that fixed it.
