### ISSUE TITLE
add sh command 

### ISSUE THREAD

**Issue by MaxAkkerman** [tonlabs/TVM-linker#223]
cd linker_lib && cargo update && sh ./build_release.sh

**Comment by buktop24** [comment]
> cd linker_lib && cargo update && sh ./build_release.sh

Hi Max and thanks for your feedback. Will add this script with the upcoming update, thanks!

**Comment by sauin** [comment]
> cd linker_lib && cargo update && sh ./build_release.sh
@MaxAkkerman the _build_release.sh_ script has the execute permission set, and this is enough for the script to run on any modern *nix-system

**Comment by sauin** [comment]
@MaxAkkerman TestSuite4 has moved to a separate [repository](https://github.com/tonlabs/TestSuite4), and the necessary permissions are already set for the build scripts (+x)
