### ISSUE TITLE
cd tvm_linker && cargo build --release

### ISSUE THREAD

**Issue by lexent3010** [tonlabs/TVM-linker#255]
Running `rustc --crate-name ton_types --edition=2018 /home/ilya/.cargo/git/checkouts/ton-labs-types-44487be4b4f492ad/da45b4f/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -Cembed-bitcode=no -C debuginfo=2 -C metadata=0371c1dceb6ef24c -C extra-filename=-0371c1dceb6ef24c --out-dir /home/ilya/TVM-linker/tvm_linker/target/debug/deps -L dependency=/home/ilya/TVM-linker/tvm_linker/target/debug/deps --extern base64=/home/ilya/TVM-linker/tvm_linker/target/debug/deps/libbase64-b4fa89014c9e32e6.rmeta --extern crc=/home/ilya/TVM-linker/tvm_linker/target/debug/deps/libcrc-2f0837ba68965e3f.rmeta --extern failure=/home/ilya/TVM-linker/tvm_linker/target/debug/deps/libfailure-78168c6ba513a415.rmeta --extern hex=/home/ilya/TVM-linker/tvm_linker/target/debug/deps/libhex-559ca24ac529256c.rmeta --extern lockfree=/home/ilya/TVM-linker/tvm_linker/target/debug/deps/liblockfree-e1237ae9544de1af.rmeta --extern log=/home/ilya/TVM-linker/tvm_linker/target/debug/deps/liblog-7eeaf9e08100c906.rmeta --extern num=/home/ilya/TVM-linker/tvm_linker/target/debug/deps/libnum-6e6af7762f91487f.rmeta --extern num_derive=/home/ilya/TVM-linker/tvm_linker/target/debug/deps/libnum_derive-ece29c0797da8aa0.so --extern num_traits=/home/ilya/TVM-linker/tvm_linker/target/debug/deps/libnum_traits-3df5953fd39d4127.rmeta --extern rand=/home/ilya/TVM-linker/tvm_linker/target/debug/deps/librand-5c663e2922003c56.rmeta --extern sha2=/home/ilya/TVM-linker/tvm_linker/target/debug/deps/libsha2-4638de69313890cd.rmeta --cap-lints allow`
error[E0277]: the trait bound `[u8; 32]: std::convert::From<std::vec::Vec<u8>>` is not satisfied
   --> /home/ilya/.cargo/git/checkouts/ton-labs-types-44487be4b4f492ad/da45b4f/src/types.rs:130:17
    |
130 |         Ok(Self(bytes.try_into().unwrap()))
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::convert::From<std::vec::Vec<u8>>` is not implemented for `[u8; 32]`
    |
    = note: required because of the requirements on the impl of `std::convert::Into<[u8; 32]>` for `std::vec::Vec<u8>`
    = note: required because of the requirements on the impl of `std::convert::TryFrom<std::vec::Vec<u8>>` for `[u8; 32]`
    = note: required because of the requirements on the impl of `std::convert::TryInto<[u8; 32]>` for `std::vec::Vec<u8>`

error[E0277]: the trait bound `[u8; 32]: std::convert::From<std::vec::Vec<u8>>` is not satisfied
   --> /home/ilya/.cargo/git/checkouts/ton-labs-types-44487be4b4f492ad/da45b4f/src/types.rs:144:35
    |
144 |         let hash: [u8; 32] = data.try_into().unwrap();
    |                                   ^^^^^^^^ the trait `std::convert::From<std::vec::Vec<u8>>` is not implemented for `[u8; 32]`
    |
    = note: required because of the requirements on the impl of `std::convert::Into<[u8; 32]>` for `std::vec::Vec<u8>`
    = note: required because of the requirements on the impl of `std::convert::TryFrom<std::vec::Vec<u8>>` for `[u8; 32]`
    = note: required because of the requirements on the impl of `std::convert::TryInto<[u8; 32]>` for `std::vec::Vec<u8>`

error[E0277]: the trait bound `[u8; 32]: std::convert::From<std::vec::Vec<u8>>` is not satisfied
   --> /home/ilya/.cargo/git/checkouts/ton-labs-types-44487be4b4f492ad/da45b4f/src/types.rs:175:14
    |
175 |         Self((0..32).map(|_| { rand::random::<u8>() }).collect::<Vec<u8>>().try_into().unwrap())
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::convert::From<std::vec::Vec<u8>>` is not implemented for `[u8; 32]`
    |
    = note: required because of the requirements on the impl of `std::convert::Into<[u8; 32]>` for `std::vec::Vec<u8>`
    = note: required because of the requirements on the impl of `std::convert::TryFrom<std::vec::Vec<u8>>` for `[u8; 32]`
    = note: required because of the requirements on the impl of `std::convert::TryInto<[u8; 32]>` for `std::vec::Vec<u8>`

error[E0277]: the trait bound `[u8; 32]: std::convert::From<std::vec::Vec<u8>>` is not satisfied
   --> /home/ilya/.cargo/git/checkouts/ton-labs-types-44487be4b4f492ad/da45b4f/src/types.rs:224:21
    |
224 |         match value.try_into() {
    |                     ^^^^^^^^ the trait `std::convert::From<std::vec::Vec<u8>>` is not implemented for `[u8; 32]`
    |
    = note: required because of the requirements on the impl of `std::convert::Into<[u8; 32]>` for `std::vec::Vec<u8>`
    = note: required because of the requirements on the impl of `std::convert::TryFrom<std::vec::Vec<u8>>` for `[u8; 32]`
    = note: required because of the requirements on the impl of `std::convert::TryInto<[u8; 32]>` for `std::vec::Vec<u8>`

error[E0599]: no method named `as_slice` found for enum `std::convert::Infallible` in the current scope
   --> /home/ilya/.cargo/git/checkouts/ton-labs-types-44487be4b4f492ad/da45b4f/src/types.rs:226:56
    |
226 |             Err(value) => UInt256::from_le_bytes(value.as_slice())
    |                                                        ^^^^^^^^ method not found in `std::convert::Infallible`

error[E0277]: the trait bound `[u8; 32]: std::convert::From<std::vec::Vec<u8>>` is not satisfied
   --> /home/ilya/.cargo/git/checkouts/ton-labs-types-44487be4b4f492ad/da45b4f/src/cell/slice.rs:498:55
    |
498 |         let hash: [u8; 32] = self.get_next_bytes(32)?.try_into().unwrap();
    |                                                       ^^^^^^^^ the trait `std::convert::From<std::vec::Vec<u8>>` is not implemented for `[u8; 32]`
    |
    = note: required because of the requirements on the impl of `std::convert::Into<[u8; 32]>` for `std::vec::Vec<u8>`
    = note: required because of the requirements on the impl of `std::convert::TryFrom<std::vec::Vec<u8>>` for `[u8; 32]`
    = note: required because of the requirements on the impl of `std::convert::TryInto<[u8; 32]>` for `std::vec::Vec<u8>`

error: aborting due to 6 previous errors

Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `ton_types`.

Caused by:
  process didn't exit successfully: `rustc --crate-name ton_types --edition=2018 /home/ilya/.cargo/git/checkouts/ton-labs-types-44487be4b4f492ad/da45b4f/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -Cembed-bitcode=no -C debuginfo=2 -C metadata=0371c1dceb6ef24c -C extra-filename=-0371c1dceb6ef24c --out-dir /home/ilya/TVM-linker/tvm_linker/target/debug/deps -L dependency=/home/ilya/TVM-linker/tvm_linker/target/debug/deps --extern base64=/home/ilya/TVM-linker/tvm_linker/target/debug/deps/libbase64-b4fa89014c9e32e6.rmeta --extern crc=/home/ilya/TVM-linker/tvm_linker/target/debug/deps/libcrc-2f0837ba68965e3f.rmeta --extern failure=/home/ilya/TVM-linker/tvm_linker/target/debug/deps/libfailure-78168c6ba513a415.rmeta --extern hex=/home/ilya/TVM-linker/tvm_linker/target/debug/deps/libhex-559ca24ac529256c.rmeta --extern lockfree=/home/ilya/TVM-linker/tvm_linker/target/debug/deps/liblockfree-e1237ae9544de1af.rmeta --extern log=/home/ilya/TVM-linker/tvm_linker/target/debug/deps/liblog-7eeaf9e08100c906.rmeta --extern num=/home/ilya/TVM-linker/tvm_linker/target/debug/deps/libnum-6e6af7762f91487f.rmeta --extern num_derive=/home/ilya/TVM-linker/tvm_linker/target/debug/deps/libnum_derive-ece29c0797da8aa0.so --extern num_traits=/home/ilya/TVM-linker/tvm_linker/target/debug/deps/libnum_traits-3df5953fd39d4127.rmeta --extern rand=/home/ilya/TVM-linker/tvm_linker/target/debug/deps/librand-5c663e2922003c56.rmeta --extern sha2=/home/ilya/TVM-linker/tvm_linker/target/debug/deps/libsha2-4638de69313890cd.rmeta --cap-lints allow` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by lexent3010** [comment]
Hello, what could cause such a situation?

**Comment by lexent3010** [comment]
Можно даже по Русски)

**Comment by joydark** [comment]
Please do `cargo update` before `cargo build --release`
Check you rustc -V >= 1.51.0
