### ISSUE TITLE
Add `Cargo.lock`

### ISSUE THREAD

**Issue by 0xdeafbeef** [tonlabs/TVM-linker#506]
You should use it to make builds reproducible.  [Link](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries). You can't build an older version without it because newer dependencies are incompatible with old code.

**Comment by NoamDev** [comment]
Moreover, sometimes some dependency gets updated and the code isn't yet compatible.
It is impossible to build even the latest version in that case.
Contests had to be prolonged for such reasons

**Comment by ilyar** [comment]
This is very important to do otherwise you will have to do [this](https://gist.github.com/ilyar/a7ca06701fa4b4e53d5cc14ec1d2c046) all the time.

**Comment by ilyar** [comment]
🎉 https://github.com/tonlabs/TVM-linker/commit/1e0014a54aecd18a17a6984db6fa6f567d633154
