### ISSUE TITLE
The difference between README.md and actual behaviour

### ISSUE THREAD

**Issue by asnov** [tonlabs/TVM-linker#508]
Hi!
This is stated in README.md in the [6) Disassembler](https://github.com/tonlabs/TVM-linker/#6-disassembler) section:
`solidity` and `fun_c` subcommands both disassemble a tvc produced by Solidity and FunC compilers respectively.

At the same time, when I try to do `tvm-linker disasm solidity` or `tvm-linker disasm fun_c` commands, it says me that such subcommands do not exist.

Did you forget to roll out these subcommands to the production or they remained from the rich past?

**Comment by SilkovAlexander** [comment]
Thank you for your feedback. This commands were moved to command `tvm_linker disasm text`. We will fix readme as soon as possible.
