### ISSUE TITLE
Reproducible error when changing linker version from "0.15.48" to "0.18.1"

### ISSUE THREAD

**Issue by kobzistiy** [tonlabs/TVM-linker#839]
[Test.sol.txt](https://github.com/tonlabs/TVM-linker/files/9817332/Test.sol.txt)

The attached contact is deployed and launched through the locklift test.
Calling the getDetails() method on version "0.18.1" gives an error
TvmException: -10
When running on version "0.15.48" no error occurs

**Comment by IgorKoval** [comment]
We have changed private selector in linker. Solidity compiler checks one selector in function `tvm.setCodeSalt(...)`, linker creates another version of selector.
Pls, use `sold` to avoid such problem: same versions of `solc` are not compatible with same versions of linker
https://github.com/tonlabs/TON-Solidity-Compiler/tree/master/sold
